---
title: "git_01"
author: "Leah Riganyan"
date: "Spring semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
WHEN early morn walks forth in sober gray,  
Then to my black-eyed maid I haste away,  
When evening sits beneath her dusky bower  
And gently sighs away the silent hour,  
The village bell alarms, away I go,  
And the vale darkens at my pensive woe.  
  
To that sweet village, where my black-eyed maid  
Doth drop a tear beneath the silent shade,  
I turn my eyes; and pensive as I go  
Curse my black stars, and bless my pleasing woe.  
   
Oft when the summer sleeps among the trees,  
Whispering faint murmurs to the scanty breeze,  
I walk the village round; if at her side  
A youth doth walk in stolen joy and pride,  
I curse my stars in bitter grief and woe,  
That made my love so high, and me so low.  
  
O should she e’er prove false, his limbs I’d tear,  
And throw all pity on the burning air;  
I’d curse bright fortune for my mixed lot,  
And then I’d die in peace, and be forgot.  
  